---
--- Generated by Luanalysis
--- Created by swift.
--- DateTime: 11/10/24 23:08

---
--- Inheritance with OOP
Account = {balance = 0}

function Account:new (o)
    o = o or {}
    self.__index = self
    setmetatable(o, self)
    return o
end



function Account:deposit (v)
    self.balance = self.balance + v
end

function Account:withdraw (v)
    if v > self.balance then error"insufficient funds" end
    self.balance = self.balance - v
end

print(a.new)
a = Account:new()
print(a.balance)



SpecialAccount = Account:new()
s = SpecialAccount:new{limit=1000.00}

function SpecialAccount:withdraw (v)
    if v - self.balance >= self:getLimit() then
        error"insufficient funds"
    end
    self.balance = self.balance - v
end

function SpecialAccount:getLimit ()
    return self.limit or 0
end

s:withdraw(80)
print(s.balance)

--print(Account.self)
--Account.__index = Account
--
--function Account:new (o)
--    o = o or {}
--    Account.__index = self
--    setmetatable(o, self)
--    return o
--end
--
--function Account:deposit (v)
--    self.balance = self.balance + v
--end
--
--function Account:withdraw (v)
--    if v > self.balance then error"insufficient funds" end
--    self.balance = self.balance - v
--end

--A = {
--    val = 5,
--    f = function(input) print(input, val) end
--}
--
--function A:new (o)
--    o = o or {}
--    self.__index = self
--    setmetatable(o, self)
--    return o
--end
--
--
--Account.new()

--a = A.new()

--a.f()




-------------------
require("verifier")

str1 = "1234 5678 2234 5678"
str2 = "1234 5678 2234 567"
str3 = "aaaa"

---
obj = ocap.altNew(verifier)
obj2 = ocap.altNew(verifier)

obj.receiveCap("io", io)

io = nil

print(obj.evilIsValid("method creation, obj1"))
print(obj2.evilIsValid("method creation, obj2"))
----