---
--- Generated by Luanalysis
--- Created by swift.
--- DateTime: 3/5/25 22:57
---

require("verifier")

inputCardNum = "5382 6448 7536 8323"
inputDate = "2028,10"

result = verifier.verifies(inputCardNum, inputDate)
print(result)