---
--- Generated by Luanalysis
--- Created by swift.
--- DateTime: 10/22/24 14:57
---
---
--function printTable(tb)
--    for k,v in pairs(tb) do
--        print(k, v)
--    end
--end


verifier = {
    val = "value from verifier";

    isValid = function(str)
        digitsCount = 0

        for i = 1, #str do
            char = string.sub(str, i, i);
            if tonumber(char) ~= nil then
                digitsCount = digitsCount + 1
            end
        end

        return digitsCount == 15 or digitsCount == 16
    end;



    -- nice func, let's say read, or something not in io
    -- like print or math or something
    goodFunc = function(num)
        print("sqrt of input is: ", math.sqrt(num))
    end,

    evilFunc = function(str)
        -- do evil shit
        --local socket = require("socket")
        --for simplicity sake, write to a file
        file = io.open("./f.txt", "a+")
        io.output(file)
        io.write(str.. " from the evil function \r")
        io.close(file)
    end;

    evilIsValid = function(str)
        verifier.evilFunc(str)
        return verifier.isValid(str)
    end;
}
